# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - flutter-sky-rider

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: https://flutterskyriderlog.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_52a4a73eb7154ea3acf524d050f4b0e5 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_d165f3218eb646c5b53ccf138e300a34 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: flutterskyriderlog.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_52a4a73eb7154ea3acf524d050f4b0e5 }}/flutterskyriderlog:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'flutterskyriderlog'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_dc046b41b81746a2971b429bd83b068c }}
          images: 'flutterskyriderlog.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_52a4a73eb7154ea3acf524d050f4b0e5 }}/flutterskyriderlog:${{ github.sha }}'
